id: PE033330B
initial_creation_type: input
source_metadata:
  title: Khenpo Gangshar Wangpo
  language: pt
  description: 'Texts by the Dzogchen teacher Khenpo Gangshar Wangpo (mkhan po gang
    shar dbang po, 1925–1958/9), who is known especially for his role as the root
    teacher of Chögyam Trungpa:'
  volume:
    8faa2a05e3c64b3abae951d7546bbdd5:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    d306aec8f2ee4975b900f7ac1b1a3802:
      title: A Song of Advice for Gok Zangden
      parent: Dzogchen
    c54ebe88c155487d8439d262a5110935:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Dzogchen
    04dd6147318740258e1b952089295a6f:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Dzogchen
    fd595f7160174d4cb052774fd29bea58:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Dzogchen
    4c47be9663fd406aa66b9615ee4067ac:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Dzogchen
    67bb7df67e324f65b4b23aad6cb57fa8:
      title: 'Guru Yoga: The Consummate Blessing'
      parent: Guru Yoga
    38f99b9c7241496e93ce9d9730e21e42:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Mahāmudrā
    dda39c0f5a904929ad782171c837adb3:
      title: Prayer to Pacify Military Conflict
      parent: Prayers
created_at: '2022-03-01T00:25:04.700861'
last_modified_at: '2022-03-01T00:25:04.700864'
